### ISSUE TITLE
Launch Checklist

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xrust#3]
In order to launch we should have:

- [x] rust as a submodule in [x-api](https://github.com/exercism/x-api/tree/master/problems)
- [x] at least 10 problems
- [x] a "how to get started" topic in the [help repo](https://github.com/exercism/docs) repo (`app/pages/languages/getting-started-with-rust.md`)
- [ ] one to a handful of people willing to check exercism regularly (daily?) for nitpicks to ensure that the track gets off on the right foot
- [ ] toggle `"active"` to `true` in `config.json`

Some tracks have been more successful than others, and I believe the key features of the successful tracks are:

* Each submission receives feedback quickly, preferably within the first 24 hours.
* The nitpicks do not direct users to do specific things, but rather ask questions challenging people to think about different aspects of their solution, or explore new aspects of the language.

For more about contributing to language tracks on exercism, check out the Problem API Contributing guide: https://github.com/exercism/x-api/blob/master/CONTRIBUTING.md

[NOTE: edited original to reflect current state of the exercism ecosystem]

**Comment by asthasr** [comment]
The Rust language has been released, so this seems like it should happen now.

**Comment by kytrinyx** [comment]
Indeed. The tests are running green.

I'll turn the track on, but we do still need a short intro to how to get started with the language (point to where/how to install it, and perhaps a tutorial or two where you can learn the basic syntax and concepts in the language.

**Comment by kytrinyx** [comment]
The documentation is here: https://github.com/exercism/docs/pull/140 - I'm deploying that now.

**Comment by kytrinyx** [comment]
I'm launching the track, but will hold off on actually announcing it for a few days so that we can catch any weird issues if they crop up.

**Comment by lpil** [comment]
:dancer: Thanks guys!

**Comment by errm** [comment]
Yay :grinning:

**Comment by yagooar** [comment]
Any news on this front? Looks like Rust still hasn't landed in exercism :( Thanks for the great job though!

**Comment by kytrinyx** [comment]
If you scroll in the "languages" list in the navbar, Rust is there. Also, `exercism fetch` should give you rust exercises (or `exercism fetch rust`)

**Comment by yagooar** [comment]
You're right. I found that browsing exercism with an iPhone 6 you can't see the full list of languages (it stops at Ruby) and you can't scroll further down. That's why I thought Rust didn't land on exercism, sorry for that.

**Comment by kytrinyx** [comment]
I didn't realize the scrolling was still broken -- I thought we had gotten it fixed. Sorry about that!

**Comment by yagooar** [comment]
No problem - thanks again for making Rust available on Exercism! :clap:
